# Generated by Django 5.2.6 on 2025-09-14 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20, unique=True, verbose_name='MovieID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='MovieTitle')),
                ('actor1_name', models.CharField(max_length=100, verbose_name='Actor1Name')),
                ('actor2_name', models.CharField(blank=True, max_length=100, verbose_name='Actor2Name')),
                ('director_name', models.CharField(max_length=100, verbose_name='DirectorName')),
                ('movie_genre', models.CharField(choices=[('COMEDY', 'Comedy'), ('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('DRAMA', 'Drama'), ('SCIFI', 'Sci-Fi'), ('HORROR', 'Horror'), ('OTHER', 'Other')], max_length=10, verbose_name='MovieGenre')),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='ReleaseYear')),
            ],
        ),
    ]
